source 'https://rubygems.org'
gem "jekyll", '~> 3.0.2'
gem "pygments.rb", '~> 0.6.3'
gem 'github-pages', '45'
gem 'nokogiri', '~> 1.6'
gem 'html5_validator', '~> 1.0'
gem 'w3c_validators', '~> 1.2'
gem 'colorize', '~> 0.7'
gem 'html-proofer', '~> 2.6'
